[package]
build   = "native/build.rs"
edition = "2021"
name    = "native"
version = "0.1.0"

[lib]
crate-type = ["dylib"]
name       = "fjall_native"
path       = "native/lib.rs"

[dependencies]
fjall   = "3"
rustler = "0.36"
